### ISSUE TITLE
Saat kedua pemain belum memilih karakter dan menekan tombol choose, halaman dapat berubah kehalaman gameplay, namun terjadi error tidak memunculkan track lari

### ISSUE THREAD

**Issue by sirpriam** [priambodop/FingerForLife#6]

**Comment by priambodop** [comment]
*Jenis HP 1: iPhone 7 Plus*Jenis Browser 1: Chrome*Jaringan Internet 1: Telkomsel*Jenis HP 2: iPhone 7 Plus*Jenis Browser 2: Safari*Jaringan Internet 2: Telkomsel*Jenis PC: Asus ROG FX*Jenis Browser: Chrome*Jaringan Internet: Wifi UNPAR9
--

**Comment by sirpriam** [comment]
*Jenis HP 1: iPhone 7 Plus
*Jenis Browser 1: Chrome
*Jaringan Internet 1: Telkomsel

*Jenis HP 2: iPhone 7 Plus
*Jenis Browser 2: Safari
*Jaringan Internet 2: Telkomsel

*Jenis PC: Asus ROG FX
*Jenis Browser: Chrome
*Jaringan Internet: Wifi UNPAR9

**Comment by sirpriam** [comment]
Jenis HP 1: iPhone 7 Plus
Jenis Browser 1: Chrome
Jaringan Internet 1: Telkomsel

Jenis HP 2: Samsung J7 Pro
Jenis Browser 2: Chrome Android
Jaringan Internet 2: Telkomsel

Jenis PC : Asus ROG FX
Jenis browser : Chrome
Jaringan internet : Wifi UNPAR9

**Comment by sirpriam** [comment]
Jenis HP 1: iPhone 7 Plus 
Jenis Browser 1: Chrome
Jaringan Internet 1: Telkomsel

Jenis HP 2: iPhone 7
Jenis Browser 2: Chrome
Jaringan Internet 2: Telkomsel

Jenis PC : Macbook Pro 13'' Mid 2014
Jenis browser : Chrome
Jaringan internet : Wifi UNPAR9

**Comment by sirpriam** [comment]
_Error_ terjadi karena pada saat halaman pemilihan karakter ditampilkan, data _value_ karakter memiliki nilai _default_ pada karakter _Summer_ _Egg_. Dengan begitu, pemain dapat langsung menekan tombol choose tanpa harus memilih karakter terlebih dahulu. Hanya saja, data _value_ karakter tersebut tidak dikirimkan ke _server_.
--

**Comment by sirpriam** [comment]
Solusi dari masalah ini adalah menggunakan JavaScript, dengan menangani kasus dimana pemain harus terlebih dahulu memilih karakter sebelum menekan tombol choose.
--

**Comment by sirpriam** [comment]
Potongan kode dari masalah ini adalah sebagai berikut:

```
var valButton = $('input[name="radioChar"]:checked').val();
  console.log(valButton);
  if (valButton === undefined) {
    alert("You have not choose a character.");
  }
  else{
    socket.emit('sendingChar', {
      val: valButton,
      id: socket.id,
      marker: 1
    });
    document.getElementById("nextButton").disabled = true;
  }
```
